name: build_debug

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.9.6'
        actions-cache-folder: '.xmake-cache'
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
        local-cache: true
    - name: 编译软件arm64-v8a
      run: |
        xmake f --host=android -m debug -a arm64-v8a -p android -y
        xmake -j8 -y -b cheat
    - uses: actions/upload-artifact@v4
      with:
        name: cheat_arm64-v8a_debug
        path: |
          build/android/arm64-v8a
    - name: 编译软件armeabi-v7a
      run: |
        xmake f --host=android -m debug -a armeabi-v7a -p android -y
        xmake -j8 -y -b cheat
    - uses: actions/upload-artifact@v4
      with:
        name: cheat_armeabi-v7a_debug
        path: |
          build/android/armeabi-v7a
